# Generated by Django 4.2.7 on 2024-03-05 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_productcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='배송비')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='총 가격')),
                ('payment_status', models.CharField(choices=[('UNPAID', '미결제'), ('PAID', '결제 완료'), ('CANCELLED', '취소'), ('REFUNDED', '환불')], max_length=50, verbose_name='결제 상태')),
                ('order_status', models.CharField(choices=[('DELIVERING', '배송중'), ('DELIVERED', '배송 완료')], max_length=50, verbose_name='주문 상태')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='주소')),
                ('name', models.CharField(max_length=30, verbose_name='구매자명')),
                ('email', models.CharField(max_length=50, verbose_name='구매자 이메일')),
                ('phone', models.CharField(max_length=30, verbose_name='구매자 핸드폰 번호')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('seller', models.ManyToManyField(blank=True, to='seller.seller', verbose_name='판매자 FK')),
            ],
            options={
                'verbose_name': '장바구니 주문',
                'verbose_name_plural': '장바구니 주문',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='장바구니 ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='수량')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='가격')),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='총 가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품 FK')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoption', verbose_name='상품 옵션 FK')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='유저 FK')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
            },
        ),
    ]
